const form=document.getElementById('checkinForm');
const pages=[...document.querySelectorAll('.page')];
const stepsEl=document.getElementById('steps');
let current=0;

pages.forEach((p,i)=>{const s=document.createElement('div');s.className='step';s.innerHTML=`<span class="step-dot">${i+1}</span><span>${p.dataset.title}</span>`;stepsEl.appendChild(s)});
const steps=[...document.querySelectorAll('.step')];
function update(){pages.forEach((p,i)=>p.classList.toggle('active',i===current));steps.forEach((s,i)=>{s.classList.toggle('active',i===current);s.classList.toggle('done',i<current)});const pct=Math.round((current/(pages.length-1))*100);document.getElementById('progressBar').style.width=pct+'%';document.getElementById('progressText').textContent=pct+'%';window.scrollTo({top:0,behavior:'smooth'})}
function validatePage(){const req=[...pages[current].querySelectorAll('[required]')];let ok=true;req.forEach(el=>{if(el.type==='radio'){if(!form.querySelector(`[name="${el.name}"]:checked`)) ok=false} else if(!el.value.trim()) ok=false});const err=pages[current].querySelector('.error');if(err){err.style.display=ok?'none':'block';err.textContent='Please complete the required question before continuing.'}return ok}
document.querySelectorAll('.next').forEach(b=>b.addEventListener('click',()=>{if(validatePage()&&current<pages.length-1){current++;update();saveDraft()}}));
document.querySelectorAll('.prev').forEach(b=>b.addEventListener('click',()=>{if(current>0){current--;update()}}));
function collect(){const fd=new FormData(form),o={};for(const [k,v] of fd.entries()){if(o[k])o[k]=Array.isArray(o[k])?[...o[k],v]:[o[k],v];else o[k]=v};const advocacy=o.advocacy||[];const adv=Array.isArray(advocacy)?advocacy:[advocacy];o.testimonial=adv.includes('Happy to provide a testimonial')?'Yes':'No';o.case_study=adv.includes('Open to a case study')?'Yes':'No';o.google_review=adv.includes('Happy to leave a Google review')?'Yes':'No';delete o.advocacy;o.services=Array.isArray(o.services)?o.services.join(', '):(o.services||'');o.business_changes=Array.isArray(o.business_changes)?o.business_changes.join(', '):(o.business_changes||'');o.priorities=Array.isArray(o.priorities)?o.priorities.join(', '):(o.priorities||'');o.submission_id='AV-'+Date.now();o.submitted_at=new Date().toISOString();o.account_manager=CONFIG.accountManager;o.health_score=health(o);o.risk_level=o.health_score<60?'At risk':o.health_score<75?'Watch':'Healthy';o.follow_up=(o.health_score<75||Number(o.avante_satisfaction||10)<7||o.could_improve)?'Yes':'No';return o}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}
function health(o){const vals=[num(o.next_quarter_confidence),num(o.avante_satisfaction),num(o.communication),num(o.response_times),num(o.business_understanding),num(o.marketing_knowledge),num(o.quality_advice),num(o.reporting),num(o.proactivity),num(o.overall_support),num(o.nps)];const good=vals.filter(v=>v!==null);return good.length?Math.round((good.reduce((a,b)=>a+b,0)/(good.length*10))*100)/100:0}
function saveDraft(){localStorage.setItem('avante_checkin_draft',JSON.stringify(collect()))}
function toggleServiceSections(){
  const selected=[...form.querySelectorAll('[name=services]:checked')].map(el=>el.value);
  document.querySelectorAll('.service-block').forEach(block=>block.classList.toggle('hidden',!selected.includes(block.dataset.service)));
  const notice=document.getElementById('noServicesNotice');
  if(notice) notice.classList.toggle('hidden',selected.length>0);
}
form.addEventListener('input',()=>{saveDraft();toggleAdvocacy();toggleServiceSections()});
function toggleAdvocacy(){const sat=Number(form.querySelector('[name=avante_satisfaction]:checked')?.value||0),nps=Number(form.querySelector('[name=nps]:checked')?.value||-1);document.getElementById('advocacy').classList.toggle('hidden',!(sat>=9||nps>=9))}
function download(data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`avante-checkin-${(data.company||'response').replace(/[^a-z0-9]+/gi,'-').toLowerCase()}-${Date.now()}.json`;a.click();URL.revokeObjectURL(a.href)}
form.addEventListener('submit',async e=>{e.preventDefault();if(!validatePage())return;const btn=document.getElementById('submitBtn');btn.disabled=true;btn.textContent='Sending…';const data=collect();let sent=false;let message='Your response was saved as a download. Add the Google Apps Script URL in CONFIG to collect responses automatically.';if(CONFIG.responseEndpoint){try{await fetch(CONFIG.responseEndpoint,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify(data)});sent=true;message='Your response has been sent to Avante.'}catch(err){message='We could not reach the response sheet, so a backup has been downloaded.'}}if(CONFIG.downloadBackup)download(data);localStorage.removeItem('avante_checkin_draft');document.getElementById('formArea').classList.add('hidden');document.getElementById('successArea').classList.remove('hidden');document.getElementById('submitStatus').textContent=message;document.getElementById('sumConfidence').textContent=data.next_quarter_confidence?data.next_quarter_confidence+'/10':'—';document.getElementById('sumSatisfaction').textContent=data.avante_satisfaction?data.avante_satisfaction+'/10':'—';document.getElementById('sumNps').textContent=data.nps!==undefined&&data.nps!==''?data.nps+'/10':'—';document.getElementById('progressBar').style.width='100%';document.getElementById('progressText').textContent='100%'});
document.getElementById('restartBtn').addEventListener('click',()=>location.reload());
// Prefill supported URL fields: ?company=Acme&client_name=Alex&quarter=Q3%202026
const params=new URLSearchParams(location.search);['company','client_name','email','quarter'].forEach(k=>{if(params.get(k)&&form.elements[k])form.elements[k].value=params.get(k)});
update();toggleAdvocacy();toggleServiceSections();
